version: '3'

networks:
  laravel:

services:
  server:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - laravel
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance_app
      MYSQL_USER: app
      MYSQL_PASSWORD: finance
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ~/.docker/data/laravel-finance:/var/lib/mysql
    networks:
       - laravel
